test_name: Inventory Management API Tests

stages:
  - name: Create new item
    request:
      url: "{tavern.env_vars.HOST}/api/items"
      method: POST
      headers:
        Content-Type: application/json
      json:
        name: "Test Laptop"
        description: "A test laptop for inventory"
        quantity: 50
        price: 999.99
        category: "Electronics"
    response:
      status_code: 201
      save:
        json:
          item_id: id

  - name: Get item by ID
    request:
      url: "{tavern.env_vars.HOST}/api/items/{item_id}"
      method: GET
    response:
      status_code: 200
      json:
        id: "{item_id}"
        name: "Test Laptop"

  - name: Get top items by category
    request:
      url: "{tavern.env_vars.HOST}/api/items/category/Electronics/top"
      method: GET
    response:
      status_code: 200
      json:
        category: "Electronics"
        items: !anything

  - name: Create temporary inventory block
    request:
      url: "{tavern.env_vars.HOST}/api/items/block/temporary"
      method: POST
      headers:
        Content-Type: application/json
      json:
        itemId: "{item_id}"
        quantity: 5
    response:
      status_code: 201
      json:
        blockId: !anyint
      save:
        json:
          block_id: blockId

  - name: Convert temporary block to permanent
    request:
      url: "{tavern.env_vars.HOST}/api/items/block/permanent"
      method: POST
      headers:
        Content-Type: application/json
      json:
        blockId: "{block_id}"
    response:
      status_code: 200

  - name: Cleanup expired blocks
    request:
      url: "{tavern.env_vars.HOST}/api/items/cleanup/expired-blocks"
      method: POST
    response:
      status_code: 200
      json:
        message: !anystr

  - name: Test invalid item creation (missing required fields)
    request:
      url: "{tavern.env_vars.HOST}/api/items"
      method: POST
      headers:
        Content-Type: application/json
      json:
        name: "Incomplete Item"
    response:
      status_code: 400

  - name: Test invalid inventory block (non-existent item)
    request:
      url: "{tavern.env_vars.HOST}/api/items/block/temporary"
      method: POST
      headers:
        Content-Type: application/json
      json:
        itemId: 999999
        quantity: 1
    response:
      status_code: 404